allowBuilds:
  '@playwright/browser-chromium': set this to true or false
  '@scarf/scarf': set this to true or false
  '@tree-sitter-grammars/tree-sitter-yaml': set this to true or false
  bufferutil: set this to true or false
  core-js-pure: set this to true or false
  tree-sitter: set this to true or false
  tree-sitter-json: set this to true or false
  unrs-resolver: set this to true or false
  utf-8-validate: set this to true or false
